/*export const lightTheme = {
    body: '#E2E2E2',
    text: '#363537',
    toggleBorder: '#FFF',
    gradient: 'linear-gradient(#39598A, #79D7ED)',
  }
  
  export const darkTheme = {
    body: '#111',
    text: '#fff',
    toggleBorder: '#6B8096',
    gradient: 'linear-gradient(#091236, #1E215D)',
  }*/

  export const pianoMode = {
    body: '#E2E2E2',
    text: '#363537',
    toggleBorder: '#FFF',
    gradient: 'linear-gradient(#39598A, #79D7ED)',
    colorQ: 'transparent',
    colorW: 'transparent',
    colorE: 'transparent',
    colorA: 'transparent',
    colorS: 'transparent',
    colorD: 'transparent',
    colorZ: 'transparent',
    colorX: 'transparent',
    colorC: 'transparent',
    opacity: 'none',
    fontFamily: 'Abril Fatface',
    fontSize: '1.35rem',
    background: '#f3d6e0',
    width: '300px',
    boxShadow: '2px 3px 3px rgba(0,0,0,0.4)',
    borderWidth: '2px 5px 0px',
    borderStyle: 'solid',
    borderColor: 'transparent rgba(0,0,0,0.1) transparent rgba(0,0,0,0.1)',
    borderWidthSharp: '2px 3px 2px 0px',
    boxShadowSharp: '0,0 1px 0px rgba(0,0,0,0.8),0 2px 2px rgba(0,0,0,0.4),0 -1px 0px #000',
  }
  
  export const drumMode = {
    body: '#111',
    text: '#fff',
    toggleBorder: '#111',
    gradient: 'linear-gradient(#091236, #1E215D)',
    top: '125px',
    colorQ: '#e44b50',
    colorW: '#ff884e',
    colorE: '#ffca46',
    colorA: '#95cb51',
    colorS: '#01b26a',
    colorD: '#0099c9',
    colorZ: '#8e61a0',
    colorX: '#f7799f',
    colorC: '#FF337D',
    width: 'var(--drum-pad-width)',
    gap: 'var(--gap)',
    template: 'repeat(auto-fill, var(--drum-pad-width))',
    opacity: '80%',
    fontFamily: 'Roboto Condensed',
    fontSize: '1.2rem',
    background: '#3b0f1e',
    width: '200px',

  }