export default [
  {
    id: "heater-1",
    colorString: "red",
    displayText: "Heater One",
    keyChar: "Q",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Heater-1.mp3",
  },
  {
    id: "heater-2",
    colorString: "orange",
    displayText: "Heater Two",
    keyChar: "W",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Heater-2.mp3",
  },
  {
    id: "heater-3",
    colorString: "yellow",
    displayText: "Heater Three",
    keyChar: "E",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Heater-3.mp3",
  },
  {
    id: "heater-4",
    colorString: "green",
    displayText: "Heater Four",
    keyChar: "A",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Heater-4_1.mp3",
  },
  {
    id: "clap",
    colorString: "blue",
    displayText: "Clap",
    keyChar: "S",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Heater-6.mp3",
  },
  {
    id: "open-hh",
    colorString: "indigo",
    displayText: "Open HH",
    keyChar: "D",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Dsc_Oh.mp3",
  },
  {
    id: "kick-n-hat",
    colorString: "purple",
    displayText: `Kick'N'Hat`,
    keyChar: "Z",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Kick_n_Hat.mp3",
  },
  {
    id: "kick",
    colorString: "pink",
    displayText: "Kick",
    keyChar: "X",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/RP4_KICK_1.mp3",
  },
  {
    id: "closed-hh",
    colorString: "fuchsia",
    displayText: "Closed HH",
    keyChar: "C",
    audioSource: "https://s3.amazonaws.com/freecodecamp/drums/Cev_H2.mp3",
  },
];
